### ISSUE TITLE
Running on mac

### ISSUE THREAD

**Issue by felipeconti** [cristo-rabani/meteor-universe-audio-recorder#1]
Hi there!

When I try "meteor add universe:audio-recorder" I got this:

 => Errors while adding packages:             

While checking for universe:audio-recorder@1.0.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for
your platform.

It works on mac?

Thanks

**Comment by cristo-rabani** [comment]
Hello, 
I published it for mac too. 
I think that it will be work now for you. 

Thanks.
